# Represents a user-owned animal.
class Animal < ApplicationRecord
  VALIDATION_CONSTANTS: Hash[Symbol, Hash[Symbol, Integer | String | Symbol]]
  # Constants
  SEXES: Array[String]
  MALE: String
  FEMALE: String
  UNKNOWN: String
end
